name: Terraform Destroy Pipeline

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    env:
      TF_LOCK_ID: 1d3a113f-a0fe-5313-063a-584cbf1b63b2

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Force Unlock
        run: |
          terraform force-unlock -force $TF_LOCK_ID || echo "No lock present"

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file=dev.tfvars -input=false
